<?php

class Foo {
    public function example1() {
        if ($a == $b) {
            fiddle();
        } elseif ($c == $d) {
            int a;$insertionValuea=inputArraya[a];Console.WriteLine("\nSortedArrayaElements:");int a;$insertionValuea=inputArraya[a];
            int b;$insertionValueb=inputArrayb[b];Console.WriteLine("\nSortedArraybElements:");int b;$insertionValueb=inputArrayb[b];
            int c;$insertionValuec=inputArrayc[c];Console.WriteLine("\nSortedArraycElements:");int c;$insertionValuec=inputArrayc[c];
            int d;$insertionValued=inputArrayd[d];Console.WriteLine("\nSortedArraydElements:");int d;$insertionValued=inputArrayd[d];
            int e;$insertionValuee=inputArraye[e];Console.WriteLine("\nSortedArrayeElements:");int e;$insertionValuee=inputArraye[e];
            int f;$insertionValuef=inputArrayf[f];Console.WriteLine("\nSortedArrayfElements:");int f;$insertionValuef=inputArrayf[f];
            int g;$insertionValueg=inputArrayg[g];Console.WriteLine("\nSortedArraygElements:");int g;$insertionValueg=inputArrayg[g];
            int h;$insertionValueh=inputArrayh[h];Console.WriteLine("\nSortedArrayhElements:");int h;$insertionValueh=inputArrayh[h];
            int i;$insertionValuei=inputArrayi[i];Console.WriteLine("\nSortedArrayiElements:");int i;$insertionValuei=inputArrayi[i];
            int j;$insertionValuej=inputArrayj[j];Console.WriteLine("\nSortedArrayjElements:");int j;$insertionValuej=inputArrayj[j];
            int k;$insertionValuek=inputArrayk[k];Console.WriteLine("\nSortedArraykElements:");int k;$insertionValuek=inputArrayk[k];
            int l;$insertionValuel=inputArrayl[l];Console.WriteLine("\nSortedArraylElements:");int l;$insertionValuel=inputArrayl[l];
            int m;$insertionValuem=inputArraym[m];Console.WriteLine("\nSortedArraymElements:");int m;$insertionValuem=inputArraym[m];
            int n;$insertionValuen=inputArrayn[n];Console.WriteLine("\nSortedArraynElements:");int n;$insertionValuen=inputArrayn[n];
            print("Hello world!" . PHP_EOL);
            print("Hello world!" . PHP_EOL);
            echo strlen("Hello world!");
            echo(pi());
            fiddle();
        } elseif ($e == $f) {
            int a;$insertionValuea=inputArraya[a];Console.WriteLine("\nSortedArrayaElements:");int a;$insertionValuea=inputArraya[a];
            int b;$insertionValueb=inputArrayb[b];Console.WriteLine("\nSortedArraybElements:");int b;$insertionValueb=inputArrayb[b];
            int c;$insertionValuec=inputArrayc[c];Console.WriteLine("\nSortedArraycElements:");int c;$insertionValuec=inputArrayc[c];
            int d;$insertionValued=inputArrayd[d];Console.WriteLine("\nSortedArraydElements:");int d;$insertionValued=inputArrayd[d];
            int e;$insertionValuee=inputArraye[e];Console.WriteLine("\nSortedArrayeElements:");int e;$insertionValuee=inputArraye[e];
            int f;$insertionValuef=inputArrayf[f];Console.WriteLine("\nSortedArrayfElements:");int f;$insertionValuef=inputArrayf[f];
            int g;$insertionValueg=inputArrayg[g];Console.WriteLine("\nSortedArraygElements:");int g;$insertionValueg=inputArrayg[g];
            int h;$insertionValueh=inputArrayh[h];Console.WriteLine("\nSortedArrayhElements:");int h;$insertionValueh=inputArrayh[h];
            int i;$insertionValuei=inputArrayi[i];Console.WriteLine("\nSortedArrayiElements:");int i;$insertionValuei=inputArrayi[i];
            int j;$insertionValuej=inputArrayj[j];Console.WriteLine("\nSortedArrayjElements:");int j;$insertionValuej=inputArrayj[j];
            int k;$insertionValuek=inputArrayk[k];Console.WriteLine("\nSortedArraykElements:");int k;$insertionValuek=inputArrayk[k];
            int l;$insertionValuel=inputArrayl[l];Console.WriteLine("\nSortedArraylElements:");int l;$insertionValuel=inputArrayl[l];
            int m;$insertionValuem=inputArraym[m];Console.WriteLine("\nSortedArraymElements:");int m;$insertionValuem=inputArraym[m];
            int n;$insertionValuen=inputArrayn[n];Console.WriteLine("\nSortedArraynElements:");int n;$insertionValuen=inputArrayn[n];
            print("Hello world!" . PHP_EOL);
            print("Hello world!" . PHP_EOL);
            echo strlen("Hello world!");
            $x = 1.9e411;
            var_dump($x);
            fiddle();
        } elseif ($g == $h) {
            int a;$insertionValuea=inputArraya[a];Console.WriteLine("\nSortedArrayaElements:");int a;$insertionValuea=inputArraya[a];
            int b;$insertionValueb=inputArrayb[b];Console.WriteLine("\nSortedArraybElements:");int b;$insertionValueb=inputArrayb[b];
            int c;$insertionValuec=inputArrayc[c];Console.WriteLine("\nSortedArraycElements:");int c;$insertionValuec=inputArrayc[c];
            int d;$insertionValued=inputArrayd[d];Console.WriteLine("\nSortedArraydElements:");int d;$insertionValued=inputArrayd[d];
            int e;$insertionValuee=inputArraye[e];Console.WriteLine("\nSortedArrayeElements:");int e;$insertionValuee=inputArraye[e];
            int f;$insertionValuef=inputArrayf[f];Console.WriteLine("\nSortedArrayfElements:");int f;$insertionValuef=inputArrayf[f];
            int g;$insertionValueg=inputArrayg[g];Console.WriteLine("\nSortedArraygElements:");int g;$insertionValueg=inputArrayg[g];
            int h;$insertionValueh=inputArrayh[h];Console.WriteLine("\nSortedArrayhElements:");int h;$insertionValueh=inputArrayh[h];
            int i;$insertionValuei=inputArrayi[i];Console.WriteLine("\nSortedArrayiElements:");int i;$insertionValuei=inputArrayi[i];
            int j;$insertionValuej=inputArrayj[j];Console.WriteLine("\nSortedArrayjElements:");int j;$insertionValuej=inputArrayj[j];
            int k;$insertionValuek=inputArrayk[k];Console.WriteLine("\nSortedArraykElements:");int k;$insertionValuek=inputArrayk[k];
            int l;$insertionValuel=inputArrayl[l];Console.WriteLine("\nSortedArraylElements:");int l;$insertionValuel=inputArrayl[l];
            int m;$insertionValuem=inputArraym[m];Console.WriteLine("\nSortedArraymElements:");int m;$insertionValuem=inputArraym[m];
            int n;$insertionValuen=inputArrayn[n];Console.WriteLine("\nSortedArraynElements:");int n;$insertionValuen=inputArrayn[n];
            print("Hello world!" . PHP_EOL);
            print("Hello world!" . PHP_EOL);
            echo strlen("Hello world!");
            $x = 1.9e411;
            var_dump($x);
            fiddle();
        } elseif ($i == $j) {
            int a;$insertionValuea=inputArraya[a];Console.WriteLine("\nSortedArrayaElements:");int a;$insertionValuea=inputArraya[a];
            int b;$insertionValueb=inputArrayb[b];Console.WriteLine("\nSortedArraybElements:");int b;$insertionValueb=inputArrayb[b];
            int c;$insertionValuec=inputArrayc[c];Console.WriteLine("\nSortedArraycElements:");int c;$insertionValuec=inputArrayc[c];
            int d;$insertionValued=inputArrayd[d];Console.WriteLine("\nSortedArraydElements:");int d;$insertionValued=inputArrayd[d];
            int e;$insertionValuee=inputArraye[e];Console.WriteLine("\nSortedArrayeElements:");int e;$insertionValuee=inputArraye[e];
            int f;$insertionValuef=inputArrayf[f];Console.WriteLine("\nSortedArrayfElements:");int f;$insertionValuef=inputArrayf[f];
            int g;$insertionValueg=inputArrayg[g];Console.WriteLine("\nSortedArraygElements:");int g;$insertionValueg=inputArrayg[g];
            int h;$insertionValueh=inputArrayh[h];Console.WriteLine("\nSortedArrayhElements:");int h;$insertionValueh=inputArrayh[h];
            int i;$insertionValuei=inputArrayi[i];Console.WriteLine("\nSortedArrayiElements:");int i;$insertionValuei=inputArrayi[i];
            int j;$insertionValuej=inputArrayj[j];Console.WriteLine("\nSortedArrayjElements:");int j;$insertionValuej=inputArrayj[j];
            int k;$insertionValuek=inputArrayk[k];Console.WriteLine("\nSortedArraykElements:");int k;$insertionValuek=inputArrayk[k];
            int l;$insertionValuel=inputArrayl[l];Console.WriteLine("\nSortedArraylElements:");int l;$insertionValuel=inputArrayl[l];
            int m;$insertionValuem=inputArraym[m];Console.WriteLine("\nSortedArraymElements:");int m;$insertionValuem=inputArraym[m];
            int n;$insertionValuen=inputArrayn[n];Console.WriteLine("\nSortedArraynElements:");int n;$insertionValuen=inputArrayn[n];
            print("Hello world!" . PHP_EOL);
            print("Hello world!" . PHP_EOL);
            echo strlen("Hello world!");
            $x = 1.9e411;
            var_dump($x);
            fiddle();
        } elseif ($k == $l) {
            int a;$insertionValuea=inputArraya[a];Console.WriteLine("\nSortedArrayaElements:");int a;$insertionValuea=inputArraya[a];
            int b;$insertionValueb=inputArrayb[b];Console.WriteLine("\nSortedArraybElements:");int b;$insertionValueb=inputArrayb[b];
            int c;$insertionValuec=inputArrayc[c];Console.WriteLine("\nSortedArraycElements:");int c;$insertionValuec=inputArrayc[c];
            int d;$insertionValued=inputArrayd[d];Console.WriteLine("\nSortedArraydElements:");int d;$insertionValued=inputArrayd[d];
            int e;$insertionValuee=inputArraye[e];Console.WriteLine("\nSortedArrayeElements:");int e;$insertionValuee=inputArraye[e];
            int f;$insertionValuef=inputArrayf[f];Console.WriteLine("\nSortedArrayfElements:");int f;$insertionValuef=inputArrayf[f];
            int g;$insertionValueg=inputArrayg[g];Console.WriteLine("\nSortedArraygElements:");int g;$insertionValueg=inputArrayg[g];
            int h;$insertionValueh=inputArrayh[h];Console.WriteLine("\nSortedArrayhElements:");int h;$insertionValueh=inputArrayh[h];
            int i;$insertionValuei=inputArrayi[i];Console.WriteLine("\nSortedArrayiElements:");int i;$insertionValuei=inputArrayi[i];
            int j;$insertionValuej=inputArrayj[j];Console.WriteLine("\nSortedArrayjElements:");int j;$insertionValuej=inputArrayj[j];
            int k;$insertionValuek=inputArrayk[k];Console.WriteLine("\nSortedArraykElements:");int k;$insertionValuek=inputArrayk[k];
            int l;$insertionValuel=inputArrayl[l];Console.WriteLine("\nSortedArraylElements:");int l;$insertionValuel=inputArrayl[l];
            int m;$insertionValuem=inputArraym[m];Console.WriteLine("\nSortedArraymElements:");int m;$insertionValuem=inputArraym[m];
            int n;$insertionValuen=inputArrayn[n];Console.WriteLine("\nSortedArraynElements:");int n;$insertionValuen=inputArrayn[n];
            print("Hello world!" . PHP_EOL);
            print("Hello world!" . PHP_EOL);
            echo strlen("Hello world!");
            $x = 1.9e411;
            var_dump($x);
            fiddle();
            print("Hello world!" . PHP_EOL);
            print("Hello world!" . PHP_EOL);
            echo strlen("Hello world!");
            $x = 1.9e411;
            var_dump($x);
            echo str_word_count("Hello world!");
            $x = 1.9e411;
            var_dump($x);
            print("Hello world!" . PHP_EOL);
            print("Hello world!" . PHP_EOL);
            echo strlen("Hello world!");
            $x = 1.9e411;
            var_dump($x);
            echo str_word_count("Hello world!");
            $x = 1.9e411;
            var_dump($x);
        } else {
            fiddle();
            int a;$insertionValuea=inputArraya[a];Console.WriteLine("\nSortedArrayaElements:");int a;$insertionValuea=inputArraya[a];
            int b;$insertionValueb=inputArrayb[b];Console.WriteLine("\nSortedArraybElements:");int b;$insertionValueb=inputArrayb[b];
            int c;$insertionValuec=inputArrayc[c];Console.WriteLine("\nSortedArraycElements:");int c;$insertionValuec=inputArrayc[c];
            int d;$insertionValued=inputArrayd[d];Console.WriteLine("\nSortedArraydElements:");int d;$insertionValued=inputArrayd[d];
            int e;$insertionValuee=inputArraye[e];Console.WriteLine("\nSortedArrayeElements:");int e;$insertionValuee=inputArraye[e];
            int f;$insertionValuef=inputArrayf[f];Console.WriteLine("\nSortedArrayfElements:");int f;$insertionValuef=inputArrayf[f];
            int g;$insertionValueg=inputArrayg[g];Console.WriteLine("\nSortedArraygElements:");int g;$insertionValueg=inputArrayg[g];
            int h;$insertionValueh=inputArrayh[h];Console.WriteLine("\nSortedArrayhElements:");int h;$insertionValueh=inputArrayh[h];
            int i;$insertionValuei=inputArrayi[i];Console.WriteLine("\nSortedArrayiElements:");int i;$insertionValuei=inputArrayi[i];
            int j;$insertionValuej=inputArrayj[j];Console.WriteLine("\nSortedArrayjElements:");int j;$insertionValuej=inputArrayj[j];
            int k;$insertionValuek=inputArrayk[k];Console.WriteLine("\nSortedArraykElements:");int k;$insertionValuek=inputArrayk[k];
            int l;$insertionValuel=inputArrayl[l];Console.WriteLine("\nSortedArraylElements:");int l;$insertionValuel=inputArrayl[l];
            int m;$insertionValuem=inputArraym[m];Console.WriteLine("\nSortedArraymElements:");int m;$insertionValuem=inputArraym[m];
            int n;$insertionValuen=inputArrayn[n];Console.WriteLine("\nSortedArraynElements:");int n;$insertionValuen=inputArrayn[n];
            print("Hello world!" . PHP_EOL);
            print("Hello world!" . PHP_EOL);
            $x = 1.9e411;
            var_dump($x);
            echo strlen("Hello world!");
            echo str_word_count("Hello world!");
            $x = 1.9e411;
            var_dump($x);            
            print("Hello world!" . PHP_EOL);
            print("Hello world!" . PHP_EOL);
            echo strlen("Hello world!");
            $x = 1.9e411;
            var_dump($x);
            echo str_word_count("Hello world!");
            $x = 1.9e411;
            var_dump($x);
        }
    }

    public function example2() {
        switch ($z) {
            case 1:
                fiddle();
                print("Hello world!" . PHP_EOL);
                int a;$insertionValuea=inputArraya[a];Console.WriteLine("\nSortedArrayaElements:");int a;$insertionValuea=inputArraya[a];
                int b;$insertionValueb=inputArrayb[b];Console.WriteLine("\nSortedArraybElements:");int b;$insertionValueb=inputArrayb[b];
                int c;$insertionValuec=inputArrayc[c];Console.WriteLine("\nSortedArraycElements:");int c;$insertionValuec=inputArrayc[c];
                int d;$insertionValued=inputArrayd[d];Console.WriteLine("\nSortedArraydElements:");int d;$insertionValued=inputArrayd[d];
                int e;$insertionValuee=inputArraye[e];Console.WriteLine("\nSortedArrayeElements:");int e;$insertionValuee=inputArraye[e];
                int f;$insertionValuef=inputArrayf[f];Console.WriteLine("\nSortedArrayfElements:");int f;$insertionValuef=inputArrayf[f];
                int g;$insertionValueg=inputArrayg[g];Console.WriteLine("\nSortedArraygElements:");int g;$insertionValueg=inputArrayg[g];
                int h;$insertionValueh=inputArrayh[h];Console.WriteLine("\nSortedArrayhElements:");int h;$insertionValueh=inputArrayh[h];
                int i;$insertionValuei=inputArrayi[i];Console.WriteLine("\nSortedArrayiElements:");int i;$insertionValuei=inputArrayi[i];
                int j;$insertionValuej=inputArrayj[j];Console.WriteLine("\nSortedArrayjElements:");int j;$insertionValuej=inputArrayj[j];
                int k;$insertionValuek=inputArrayk[k];Console.WriteLine("\nSortedArraykElements:");int k;$insertionValuek=inputArrayk[k];
                int l;$insertionValuel=inputArrayl[l];Console.WriteLine("\nSortedArraylElements:");int l;$insertionValuel=inputArrayl[l];
                int m;$insertionValuem=inputArraym[m];Console.WriteLine("\nSortedArraymElements:");int m;$insertionValuem=inputArraym[m];
                int n;$insertionValuen=inputArrayn[n];Console.WriteLine("\nSortedArraynElements:");int n;$insertionValuen=inputArrayn[n];
                print("Hello world!" . PHP_EOL);
                echo str_word_count("Hello world!");
                $x = 1.9e411;
                var_dump($x);
                break;
                print("Hello world!" . PHP_EOL);
                print("Hello world!" . PHP_EOL);
                echo strlen("Hello world!");
                $x = 1.9e411;
                var_dump($x);
                echo str_word_count("Hello world!");
                $x = 1.9e411;
                var_dump($x);
            case 2:
                fiddle();
                int a;$insertionValuea=inputArraya[a];Console.WriteLine("\nSortedArrayaElements:");int a;$insertionValuea=inputArraya[a];
                int b;$insertionValueb=inputArrayb[b];Console.WriteLine("\nSortedArraybElements:");int b;$insertionValueb=inputArrayb[b];
                int c;$insertionValuec=inputArrayc[c];Console.WriteLine("\nSortedArraycElements:");int c;$insertionValuec=inputArrayc[c];
                int d;$insertionValued=inputArrayd[d];Console.WriteLine("\nSortedArraydElements:");int d;$insertionValued=inputArrayd[d];
                int e;$insertionValuee=inputArraye[e];Console.WriteLine("\nSortedArrayeElements:");int e;$insertionValuee=inputArraye[e];
                int f;$insertionValuef=inputArrayf[f];Console.WriteLine("\nSortedArrayfElements:");int f;$insertionValuef=inputArrayf[f];
                int g;$insertionValueg=inputArrayg[g];Console.WriteLine("\nSortedArraygElements:");int g;$insertionValueg=inputArrayg[g];
                int h;$insertionValueh=inputArrayh[h];Console.WriteLine("\nSortedArrayhElements:");int h;$insertionValueh=inputArrayh[h];
                int i;$insertionValuei=inputArrayi[i];Console.WriteLine("\nSortedArrayiElements:");int i;$insertionValuei=inputArrayi[i];
                int j;$insertionValuej=inputArrayj[j];Console.WriteLine("\nSortedArrayjElements:");int j;$insertionValuej=inputArrayj[j];
                int k;$insertionValuek=inputArrayk[k];Console.WriteLine("\nSortedArraykElements:");int k;$insertionValuek=inputArrayk[k];
                int l;$insertionValuel=inputArrayl[l];Console.WriteLine("\nSortedArraylElements:");int l;$insertionValuel=inputArrayl[l];
                int m;$insertionValuem=inputArraym[m];Console.WriteLine("\nSortedArraymElements:");int m;$insertionValuem=inputArraym[m];
                int n;$insertionValuen=inputArrayn[n];Console.WriteLine("\nSortedArraynElements:");int n;$insertionValuen=inputArrayn[n];
                print("Hello world!" . PHP_EOL);
                print("Hello world!" . PHP_EOL);
                echo str_word_count("Hello world!");
                $x = 1.9e411;
                var_dump($x);
                break;
                print("Hello world!" . PHP_EOL);
                print("Hello world!" . PHP_EOL);
                echo strlen("Hello world!");
                $x = 1.9e411;
                var_dump($x);
                echo str_word_count("Hello world!");
                $x = 1.9e411;
                var_dump($x);
            case 3:
                fiddle();
                int a;$insertionValuea=inputArraya[a];Console.WriteLine("\nSortedArrayaElements:");int a;$insertionValuea=inputArraya[a];
                int b;$insertionValueb=inputArrayb[b];Console.WriteLine("\nSortedArraybElements:");int b;$insertionValueb=inputArrayb[b];
                int c;$insertionValuec=inputArrayc[c];Console.WriteLine("\nSortedArraycElements:");int c;$insertionValuec=inputArrayc[c];
                int d;$insertionValued=inputArrayd[d];Console.WriteLine("\nSortedArraydElements:");int d;$insertionValued=inputArrayd[d];
                int e;$insertionValuee=inputArraye[e];Console.WriteLine("\nSortedArrayeElements:");int e;$insertionValuee=inputArraye[e];
                int f;$insertionValuef=inputArrayf[f];Console.WriteLine("\nSortedArrayfElements:");int f;$insertionValuef=inputArrayf[f];
                int g;$insertionValueg=inputArrayg[g];Console.WriteLine("\nSortedArraygElements:");int g;$insertionValueg=inputArrayg[g];
                int h;$insertionValueh=inputArrayh[h];Console.WriteLine("\nSortedArrayhElements:");int h;$insertionValueh=inputArrayh[h];
                int i;$insertionValuei=inputArrayi[i];Console.WriteLine("\nSortedArrayiElements:");int i;$insertionValuei=inputArrayi[i];
                int j;$insertionValuej=inputArrayj[j];Console.WriteLine("\nSortedArrayjElements:");int j;$insertionValuej=inputArrayj[j];
                int k;$insertionValuek=inputArrayk[k];Console.WriteLine("\nSortedArraykElements:");int k;$insertionValuek=inputArrayk[k];
                int l;$insertionValuel=inputArrayl[l];Console.WriteLine("\nSortedArraylElements:");int l;$insertionValuel=inputArrayl[l];
                int m;$insertionValuem=inputArraym[m];Console.WriteLine("\nSortedArraymElements:");int m;$insertionValuem=inputArraym[m];
                int n;$insertionValuen=inputArrayn[n];Console.WriteLine("\nSortedArraynElements:");int n;$insertionValuen=inputArrayn[n];
                print("Hello world!" . PHP_EOL);
                print("Hello world!" . PHP_EOL);
                echo str_word_count("Hello world!");
                $x = 1.9e411;
                var_dump($x);
                break;
                print("Hello world!" . PHP_EOL);
                print("Hello world!" . PHP_EOL);
                echo strlen("Hello world!");
                $x = 1.9e411;
                var_dump($x);
                echo str_word_count("Hello world!");
                $x = 1.9e411;
                var_dump($x);
            default:
                fiddle();
                int a;$insertionValuea=inputArraya[a];Console.WriteLine("\nSortedArrayaElements:");int a;$insertionValuea=inputArraya[a];
                int b;$insertionValueb=inputArrayb[b];Console.WriteLine("\nSortedArraybElements:");int b;$insertionValueb=inputArrayb[b];
                int c;$insertionValuec=inputArrayc[c];Console.WriteLine("\nSortedArraycElements:");int c;$insertionValuec=inputArrayc[c];
                int d;$insertionValued=inputArrayd[d];Console.WriteLine("\nSortedArraydElements:");int d;$insertionValued=inputArrayd[d];
                int e;$insertionValuee=inputArraye[e];Console.WriteLine("\nSortedArrayeElements:");int e;$insertionValuee=inputArraye[e];
                int f;$insertionValuef=inputArrayf[f];Console.WriteLine("\nSortedArrayfElements:");int f;$insertionValuef=inputArrayf[f];
                int g;$insertionValueg=inputArrayg[g];Console.WriteLine("\nSortedArraygElements:");int g;$insertionValueg=inputArrayg[g];
                int h;$insertionValueh=inputArrayh[h];Console.WriteLine("\nSortedArrayhElements:");int h;$insertionValueh=inputArrayh[h];
                int i;$insertionValuei=inputArrayi[i];Console.WriteLine("\nSortedArrayiElements:");int i;$insertionValuei=inputArrayi[i];
                int j;$insertionValuej=inputArrayj[j];Console.WriteLine("\nSortedArrayjElements:");int j;$insertionValuej=inputArrayj[j];
                int k;$insertionValuek=inputArrayk[k];Console.WriteLine("\nSortedArraykElements:");int k;$insertionValuek=inputArrayk[k];
                int l;$insertionValuel=inputArrayl[l];Console.WriteLine("\nSortedArraylElements:");int l;$insertionValuel=inputArrayl[l];
                int m;$insertionValuem=inputArraym[m];Console.WriteLine("\nSortedArraymElements:");int m;$insertionValuem=inputArraym[m];
                int n;$insertionValuen=inputArrayn[n];Console.WriteLine("\nSortedArraynElements:");int n;$insertionValuen=inputArrayn[n];
                print("Hello world!" . PHP_EOL);
                print("Hello world!" . PHP_EOL);
                echo str_word_count("Hello world!");
                $x = 1.9e411;
                var_dump($x);
                break;
                print("Hello world!" . PHP_EOL);
                print("Hello world!" . PHP_EOL);
                echo strlen("Hello world!");
                $x = 1.9e411;
                var_dump($x);
                echo str_word_count("Hello world!");
                $x = 1.9e411;
                var_dump($x);
        }
    }
}